import io
import os

with open('core/views/report_views.py', 'r', encoding='utf-8') as f:
    lines = f.read().splitlines()

new_content = '\n'.join(lines[:500]) + '''
def _make_settlement_watermark_footer():
    def watermark_cb(canvas, doc):
        canvas.saveState()
        page_width, page_height = A4
        
        # Watermark
        canvas.setFont('Helvetica-Bold', 45)
        canvas.setStrokeColorRGB(0.9, 0.9, 0.9)
        canvas.setFillColorRGB(0.92, 0.92, 0.92)
        canvas.translate(page_width/2, page_height/2)
        canvas.rotate(45)
        canvas.drawCentredString(0, 0, "GROUPSATHI SETTLEMENT")
        canvas.restoreState()
        
        # Footer Disclaimer
        canvas.saveState()
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.gray)
        disclaimer = (
            "This report is generated by system and does not require any physical signature of GroupSathi. "
            "This report will be verified by group leaders,"
        )
        disclaimer2 = "and all reports are calculated based on the transaction only."
        canvas.drawCentredString(page_width/2, 0.6 * inch, disclaimer)
        canvas.drawCentredString(page_width/2, 0.45 * inch, disclaimer2)
        canvas.restoreState()
    return watermark_cb


@login_required_custom
@ratelimit(key='ip', rate='10/h', block=True)
def generate_settlement_pdf(request, group_id):
    """Generate a settlement distribution plan PDF."""
    user_id = request.session['user_id']
    groups = get_collection('groups')
    group = groups.find_one({'group_id': group_id})
    if not group:
        messages.error(request, 'Group not found.')
        return redirect('my_groups')

    gm = get_collection('group_members')
    membership = gm.find_one({'group_id': group_id, 'user_id': user_id, 'status': 'active'})
    if not membership:
        messages.error(request, 'Access denied.')
        return redirect('my_groups')

    from core.utils import calculate_settlement_plan
    plan_data_res = calculate_settlement_plan(group_id)
    if not plan_data_res:
        messages.error(request, 'Unable to calculate settlement plan.')
        return redirect('group_detail', group_id=group_id)
        
    total_cash = plan_data_res['total_cash']
    group_profit = plan_data_res['group_profit']
    total_group_contributions = plan_data_res['total_group_contributions']
    total_final_payout = plan_data_res['total_final_payout']
    member_plans = plan_data_res['member_plans']

    # Build PDF
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=0.7 * inch, bottomMargin=1.0 * inch,
        leftMargin=0.6 * inch, rightMargin=0.6 * inch,
    )
    styles = getSampleStyleSheet()
    elements = []

    app_title_style = ParagraphStyle(
        'AppTitle', parent=styles['Title'],
        fontSize=22, textColor=ACCENT, alignment=TA_CENTER, spaceAfter=2,
    )
    group_title_style = ParagraphStyle(
        'GroupTitle', parent=styles['Title'],
        fontSize=16, textColor=PRIMARY_DARK, alignment=TA_CENTER, spaceAfter=2,
    )
    sub_style = ParagraphStyle(
        'SubInfo', parent=styles['Normal'],
        fontSize=9, textColor=colors.grey, alignment=TA_CENTER,
    )

    logo_path = os.path.join(settings.BASE_DIR, 'static', 'images', 'GroupSathi.png')
    if os.path.exists(logo_path):
        img = Image(logo_path, width=1.8*inch, height=1.8*inch, mask='auto')
        img.hAlign = 'CENTER'
        elements.append(img)
        elements.append(Spacer(1, 0.1 * inch))
    else:
        elements.append(Paragraph("GroupSathi", app_title_style))
        elements.append(Paragraph("Empowering Self Help Groups with Digital Ledgers", sub_style))
        elements.append(Spacer(1, 0.15 * inch))

    elements.append(HRFlowable(width="100%", thickness=1.5, color=ACCENT))
    elements.append(Spacer(1, 0.15 * inch))
    elements.append(Paragraph(f"{group['name']} - Settlement Report", group_title_style))
    elements.append(Paragraph(f"Group ID: <b>{group['group_id']}</b> | Date: <b>{datetime.now().strftime('%d %b %Y')}</b>", sub_style))
    elements.append(Spacer(1, 0.25 * inch))

    # Summary
    summary_data = [
        ['Total Cash Available', f"Rs. {total_cash:,.2f}"],
        ['Distributable Profit', f"Rs. {group_profit:,.2f}"],
        ['Total Paid Contributions', f"Rs. {total_group_contributions:,.2f}"],
        ['Total Final Payout', f"Rs. {total_final_payout:,.2f}"]
    ]
    t_summary = Table(summary_data, colWidths=[3*inch, 2*inch])
    t_summary.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8f9fa')),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.HexColor('#333333')),
        ('ALIGN', (0,0), (0,-1), 'LEFT'),
        ('ALIGN', (1,0), (1,-1), 'RIGHT'),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 1, colors.HexColor('#dee2e6')),
    ]))
    elements.append(t_summary)
    elements.append(Spacer(1, 0.25 * inch))

    # Formula
    formula_style = ParagraphStyle('Formula', parent=styles['Normal'], fontSize=9, textColor=colors.HexColor('#0d6efd'))
    elements.append(Paragraph("<b>Calculations (Single-Pass Deterministic):</b>", formula_style))
    elements.append(Paragraph("1. Member Contribution = Total EMI/contributions actually paid", formula_style))
    elements.append(Paragraph("2. Group Profit = Only collected interest + collected fines", formula_style))
    elements.append(Paragraph("3. Profit Share = Group Profit * (Member Contribution / Total Group Contributions)", formula_style))
    elements.append(Paragraph("4. Net Payout = max(0, Contribution + Profit Share - Deductions)", formula_style))
    elements.append(Spacer(1, 0.25 * inch))

    # Member Plan Table
    plan_data = [['Member Name', 'Contribution', 'Profit Share', 'Gross Settl.', 'Deductions', 'Net Payout']]
    for p in member_plans:
        payout_str = f"+Rs. {p['final_payout']:,.2f}" if p['final_payout'] > 0 else "Rs. 0.00"
        if p['remaining_due'] > 0:
            payout_str = f"Owes Rs. {p['remaining_due']:,.2f}"
            
        plan_data.append([
            f"{p['name']} ({p['role'].title()})",
            f"Rs. {p['paid_contribution']:,.2f}",
            f"Rs. {p['profit_share']:,.2f}",
            f"Rs. {p['gross_settlement']:,.2f}",
            f"-Rs. {p['total_deduction']:,.2f}" if p['total_deduction'] > 0 else "Rs. 0.00",
            payout_str
        ])
    
    t_plan = Table(plan_data, colWidths=[1.8*inch, 1.0*inch, 1.0*inch, 1.1*inch, 1.1*inch, 1.0*inch])
    t_plan.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), PRIMARY_DARK),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (0, -1), 'LEFT'),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6')),
    ]))
    elements.append(t_plan)

    cb = _make_settlement_watermark_footer()
    doc.build(elements, onFirstPage=cb, onLaterPages=cb)
    buf.seek(0)

    safe_name = group['name'].replace(' ', '_')
    filename = f"GroupSathi_{safe_name}_Settlement_Report.pdf"

    response = HttpResponse(buf, content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    return response
'''

with open('core/views/report_views.py', 'w', encoding='utf-8') as f:
    f.write(new_content)
